version: "3.7"

services:
  db:
    image: postgres:15
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370